apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: retrofit-jenkins-argocd
  title: Integrating CI/CD Into Existing Repo
  description: Inject CI/CD directly into Desired Repo/Branch

spec:
  owner: development
  type: service
  parameters:
    - title: Select Repo
      required:
        - repo
        - component_id

      properties:
        repo:
          title: Select Repository
          type: string
          # ui:field: RepoDropdown
        component_id:
          title: Component Name
          type: string
        environment:
          title: Environment
          type: string
          enum:
            - dev
            - prod
  steps:
    - id: fetch-base
      name: Fetch Template Files
      action: fetch:template
      input:
        url: ./template
        values:
          app_name: ${{ parameters.component_id }}
          app_env: ${{ parameters.environment }}
          
    # - id: register
    #   name: Register in Catalog
    #   action: catalog:register
    #   input:
    #     repoContentsUrl: https://github.com/BackstageSSPPoC/${{ parameters.repo }}/blob/main
    #     catalogInfoPath: /catalog-info.yaml
    #     optional: true

    - id: push-to-main
      name: Inject CI/CD Directly
      action: github:push
      input:
        repoUrl: github.com?owner=BackstageSSPPoC&repo=${{ parameters.repo }}
        branch: main
        commitMessage: "chore: inject CI/CD template"
        sourcePath: ./

  output:
    links:
      - title: View Repository
        url: https://github.com/BackstageSSPPoC/${{ parameters.repo }}/tree/main
